# Generated by Django 4.2.2 on 2023-06-11 11:20

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        BtreeGinExtension(),

        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=255)),
                ('photo', models.ImageField(upload_to='employee_photos')),
                ('position', models.CharField(choices=[('Дир', 'Директор'), ('Сотр', 'Сотрудник')], default='Сотр', max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department', to='company_structure.department')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='director',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director', to='company_structure.employee'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='search_idx_employee'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('full_name', 'department'), name='unique_fullname_department'),
        ),
    ]
